version: '3.0'

services:
  user-service:
    container_name: user-service
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
    ports:
      - "${USER_PORT}:${USER_PORT}"
    command: npm run start
    depends_on:
      - user-db
    environment:
      DATABASE_URL: postgres://${USER_POSTGRES_USER}:${USER_POSTGRES_PASSWORD}@user-db:5432/${USER_POSTGRES_DB}
    restart: always

  user-db:
    container_name: user-db
    image: ${USER_DB_IMAGE}
    env_file:
      - .production.env
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${USER_DB_PORT}:5432"
    volumes:
      - type: volume
        source: pgdata-user
        target: /var/lib/postgresql/data
    restart: always

  

volumes:
  pgdata-user:
    driver: local
